19-03-22 20:48:28 DEBUG {2132-8884 Main._store:144} {'assettype': 1, 'domain': '', 'protocol': 'tcp', 'service': "https web application  server: ['apache']", 'position': '', 'ip': '111.205.207.140', 'proext': 'https', 'banner': 'Index of /', 'port': '443'}
19-03-22 20:51:10 INFO {18828-19356 Main._store:134} Start collecting results information.........
19-03-22 20:51:13 DEBUG {18828-19356 Main._store:147} {'assettype': 1, 'domain': '', 'protocol': 'tcp', 'service': "https web application  server: ['apache']", 'position': '', 'ip': '111.205.207.140', 'proext': 'https', 'banner': 'Index of /', 'port': '443'}
19-03-22 20:53:02 INFO {10188-16668 Main._store:135} Start collecting results information.........
19-03-22 20:53:05 DEBUG {10188-16668 Main._store:148} {'assettype': 1, 'domain': '', 'protocol': 'tcp', 'service': "https web application  server: ['apache']", 'position': '', 'ip': '111.205.207.140', 'proext': 'https', 'banner': 'Index of /', 'port': '443'}
19-03-22 20:55:31 INFO {18096-17076 Main._store:135} Start collecting results information.........
19-03-22 20:55:34 DEBUG {18096-17076 Main._store:148} {'assettype': 1, 'domain': '', 'protocol': 'tcp', 'service': "https web application  server: ['apache']", 'position': '', 'ip': '111.205.207.140', 'proext': 'https', 'banner': 'Index of /', 'port': '443'}
19-03-22 20:55:45 INFO {18096-376 Main._run:132} task is finished and status is True
19-03-22 21:21:57 WARNING {19332-10616 IPlugin.cmd_run:157} Traceback (most recent call last):
  File "E:\Penetration\Assert_Scan\IPlugin.py", line 153, in cmd_run
    self._run(*args,**kwargs)
  File "E:/Penetration/Assert_Scan/Main.py", line 119, in _run
    self.init_db()
  File "E:/Penetration/Assert_Scan/Main.py", line 35, in init_db
    self.db = sqlite3_db(self.portdb)
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 8, in __init__
    self._create_sqlite3_connector()
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 59, in _create_sqlite3_connector
    raise Exception(errMsg)
Exception: sql requires 'python-sqlite' third-party library in order to directly connect to the database 'E:/Penetration/Assert_Scan\repertory\2019-03-22 21:21:57.db'

19-03-22 21:22:40 WARNING {11384-14760 IPlugin.cmd_run:157} Traceback (most recent call last):
  File "E:\Penetration\Assert_Scan\IPlugin.py", line 153, in cmd_run
    self._run(*args,**kwargs)
  File "E:/Penetration/Assert_Scan/Main.py", line 119, in _run
    self.init_db()
  File "E:/Penetration/Assert_Scan/Main.py", line 35, in init_db
    self.db = sqlite3_db(self.portdb)
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 8, in __init__
    self._create_sqlite3_connector()
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 59, in _create_sqlite3_connector
    raise Exception(errMsg)
Exception: sql requires 'python-sqlite' third-party library in order to directly connect to the database 'E:/Penetration/Assert_Scan\repertory\2019-03-22_21:22:40.db'

19-03-22 21:23:18 WARNING {18992-14764 IPlugin.cmd_run:157} Traceback (most recent call last):
  File "E:\Penetration\Assert_Scan\IPlugin.py", line 153, in cmd_run
    self._run(*args,**kwargs)
  File "E:/Penetration/Assert_Scan/Main.py", line 119, in _run
    self.init_db()
  File "E:/Penetration/Assert_Scan/Main.py", line 36, in init_db
    self.db.create_table(SQL)
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 72, in create_table
    self.cursor.execute(sql)
OperationalError: table "asset" has more than one primary key

19-03-22 21:23:48 WARNING {4976-15972 IPlugin.cmd_run:157} Traceback (most recent call last):
  File "E:\Penetration\Assert_Scan\IPlugin.py", line 153, in cmd_run
    self._run(*args,**kwargs)
  File "E:/Penetration/Assert_Scan/Main.py", line 119, in _run
    self.init_db()
  File "E:/Penetration/Assert_Scan/Main.py", line 36, in init_db
    self.db.create_table(SQL)
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 72, in create_table
    self.cursor.execute(sql)
OperationalError: near ")": syntax error

19-03-22 21:24:03 WARNING {18104-10328 IPlugin.cmd_run:157} Traceback (most recent call last):
  File "E:\Penetration\Assert_Scan\IPlugin.py", line 153, in cmd_run
    self._run(*args,**kwargs)
  File "E:/Penetration/Assert_Scan/Main.py", line 119, in _run
    self.init_db()
  File "E:/Penetration/Assert_Scan/Main.py", line 36, in init_db
    self.db.create_table(SQL)
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 72, in create_table
    self.cursor.execute(sql)
OperationalError: near ")": syntax error

19-03-22 21:26:30 INFO {19312-16084 Main.init_db:37} database initialization completed and dbname is 2019-03-22_21_26_29.db
19-03-22 21:26:55 WARNING {15124-18612 IPlugin.cmd_run:157} Traceback (most recent call last):
  File "E:\Penetration\Assert_Scan\IPlugin.py", line 153, in cmd_run
    self._run(*args,**kwargs)
  File "E:/Penetration/Assert_Scan/Main.py", line 119, in _run
    self.init_db()
  File "E:/Penetration/Assert_Scan/Main.py", line 36, in init_db
    self.db.create_table(SQL)
  File "E:\Penetration\Assert_Scan\common\db\sqlite3_db.py", line 72, in create_table
    self.cursor.execute(sql)
OperationalError: near ")": syntax error

19-03-22 21:28:02 INFO {8740-18240 Main.init_db:37} database initialization completed and dbname is 2019-03-22_21_28_02.db
19-03-22 21:31:50 INFO {18656-18932 Main._store:149} Start collecting results information.........
19-03-22 21:31:50 INFO {18656-18696 Main.init_db:37} database initialization completed and dbname is 2019-03-22_21_31_50.db
19-03-22 21:31:50 INFO {18656-18696 Main._run:120} tasks start running
19-03-22 21:32:03 INFO {18656-18696 Main._run:146} task is finished
19-03-22 21:33:55 INFO {888-9144 Main._store:149} Start collecting results information.........
19-03-22 21:33:56 INFO {888-17712 Main.init_db:37} database initialization completed and dbname is 2019-03-22_21_33_55.db
19-03-22 21:33:56 INFO {888-17712 Main._run:120} tasks start running
19-03-22 21:34:09 INFO {888-17712 Main._run:146} task is finished
19-03-22 21:40:09 INFO {16816-15112 Main._store:150} Start collecting results information.........
19-03-22 21:40:10 INFO {16816-12292 Main.init_db:38} database initialization completed and dbname is 2019-03-22_21_40_09.db
19-03-22 21:40:10 INFO {16816-12292 Main._run:121} tasks start running
19-03-22 21:40:22 INFO {16816-12292 Main._run:147} task is finished
19-03-22 21:43:01 INFO {17256-16932 Main._store:150} Start collecting results information.........
19-03-22 21:43:01 INFO {17256-2568 Main.init_db:38} database initialization completed and dbname is 2019-03-22_21_43_01.db
19-03-22 21:43:01 INFO {17256-2568 Main._run:121} tasks start running
19-03-22 21:43:15 INFO {17256-2568 Main._run:147} task is finished
19-03-22 21:44:36 INFO {9944-2300 Main._store:150} Start collecting results information.........
19-03-22 21:44:36 INFO {9944-1708 Main.init_db:38} database initialization completed and dbname is 2019-03-22_21_44_36.db
19-03-22 21:44:36 INFO {9944-1708 Main._run:121} tasks start running
19-03-22 21:44:49 INFO {9944-1708 Main._run:147} task is finished
19-03-22 22:02:02 INFO {16144-9680 Main._store:152} Start collecting results information.........
19-03-22 22:02:03 INFO {16144-8204 Main.init_db:40} database initialization completed
19-03-22 22:02:03 INFO {16144-8204 Main._run:123} tasks start running
19-03-22 22:02:16 INFO {16144-8204 Main._run:149} task is finished
